Solidus/ClassEvalDecorator:
  Description: 'Checks if Class.class_eval is being used in the code'
  Enabled: true
  VersionAdded: '0.1.1'

Solidus/ReimbursementHookDeprecated:
  Description: 'Checks if reimbursement_success_hooks and reimbursement_failed_hooks is being used'
  Enabled: true
  VersionAdded: '<<next>>'

Solidus/SpreeGatewayBogusDeprecated:
  Description: 'Checks if SpreeGatewayBogus is being used and replaces it with Spree::PaymentMethod::BogusCreditCard'
  Enabled: true
  VersionAdded: '<<next>>'

Solidus/SpreeTDecprecated:
  Description: 'Checks if Spree.t is being used and replaces it with I18n.t.'
  Enabled: true
  VersionAdded: '0.1.2'

Solidus/TaxCategoryDeprecated:
  Description: 'Checks if .tax_category=Instance is being used and suggest to replace it with .tax_categories=<Array of Instances>'
  Enabled: true
  VersionAdded: '<<next>>'
